'use client';
import Link from 'next/link';

export default function CryptoTerms() {
  return (
    <main style={{ maxWidth: 780, margin: '0 auto', padding: '80px 24px', color: '#eaf3ea', fontFamily: 'Inter, sans-serif', lineHeight: 1.7 }}>
      <Link href="/" style={{ color: '#9bfd4e', fontSize: 13, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 6, marginBottom: 40 }}>
        ← Back to gethstake.com
      </Link>
      <h1 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 28, marginBottom: 8 }}>Cryptocurrency Terms</h1>
      <p style={{ color: '#5f7062', fontSize: 13, marginBottom: 40 }}>Conditions for participation in cryptocurrency staking — June 2026</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>1. Nature of Digital Assets</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>Ethereum (ETH) and other digital assets are not legal tender, are not backed by any government, and their value can fluctuate significantly. Past performance does not predict future results. You acknowledge that you understand the speculative nature of digital assets.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>2. Staking Mechanics</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>Ethereum staking under Proof-of-Stake requires validators to lock ETH as collateral. Rewards are generated by attesting to blocks and proposing new ones. Rewards are variable and depend on total network stake, validator performance, and MEV conditions.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>3. Slashing Risk</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>Slashing is a penalty applied by the Ethereum protocol when validators behave dishonestly or experience critical failures (e.g., double-signing). Slashing results in a reduction of the validator's staked ETH. While gethstake employs best-practice infrastructure to minimize this risk, it cannot be entirely eliminated. The reserve fund partially covers slashing losses.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>4. Validator Queue</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>The Ethereum network limits how quickly validators can enter or exit. Entry and exit queues can extend from days to weeks depending on network demand. This affects when your ETH begins earning rewards and when withdrawal becomes available after the lock period ends.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>5. Smart Contract Risk</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>The platform's smart contracts have been audited by Hacken. However, no audit guarantees the complete absence of vulnerabilities. Bugs, exploits, or unforeseen interactions with the Ethereum protocol could result in partial or total loss of staked funds.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>6. Regulatory Risk</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>The regulatory treatment of cryptocurrency staking varies by jurisdiction and is evolving. Changes in law or regulation could affect your ability to participate, withdraw, or receive staking rewards. You are responsible for understanding and complying with the laws of your jurisdiction.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>7. Restricted Jurisdictions</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>Residents of jurisdictions where cryptocurrency staking or digital asset services are prohibited or restricted are not permitted to use the platform. You represent and warrant that your participation does not violate local laws.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>8. Tax Obligations</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>Staking rewards may be subject to income tax, capital gains tax, or other taxes depending on your jurisdiction. gethstake does not provide tax reporting or advice. You are solely responsible for calculating, reporting, and paying any taxes owed on staking income.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>9. Non-Custodial Principle</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>gethstake is designed on a non-custodial basis. Your ETH is staked via smart contracts and custody infrastructure — not held by gethstake directly. You retain control of your private keys and wallet. Loss of access to your wallet may result in permanent loss of access to your staked funds.</p>

      <h2 style={{ fontFamily: "'Chakra Petch', sans-serif", fontSize: 16, color: '#9bfd4e', marginBottom: 12, marginTop: 36 }}>10. Contact</h2>
      <p style={{ color: '#8a9b8c', marginBottom: 16 }}>For cryptocurrency-related questions: <span style={{ color: '#9bfd4e' }}>legal@gethstake.com</span></p>
    </main>
  );
}
